### ISSUE TITLE
.write() response is HTML dump

### ISSUE THREAD

**Issue by nickever** [beebotte/bbt_python#12]
I'm attempting to build some basic error handling into my script. Starting with a basic read of the response from the bbt_python write() function.

```
response = resource.write(value)
if response is True:
     pass
else:
     raise SomeKindOfError
```

However, if the RPi is disconnected from the internet, then the response returned from the write function is a long string of html, instead of the expected error as defined in __processResponse__.
[writeresponse.txt](https://github.com/beebotte/bbt_python/files/1801902/writeresponse.txt)

**Comment by bachwehbi** [comment]
The HTML dump you are getting seems to be sent by your `Sky Hub`.

Can you please share what you get with `print (r)` just after line 209 https://github.com/beebotte/bbt_python/blob/master/beebotte/__init__.py#L209

**Comment by nickever** [comment]
Hi bachwehbi, thanks for your response. I've cloned this repo and amended with print(r) after line 209 and then re-installed beebotte on my rPi from the amended clone. 

Print(r) returned `<Response [200]>`
(rPi connected to a network, but internet disconnected)

**Comment by bachwehbi** [comment]
Your Hub is replying with HTTP 200 and the code thinks everything is fine.

Can you use HTTPS? In any case, this is a better option.

```
bbt = BBT( _accesskey, _secretkey, port = "443", ssl = True)
```

Just trying to figure out how to hit a timeout and not the automatic response by the Hub.

**Comment by nickever** [comment]
Perfect, now we hit the timeout code `NewConnectionError`. I missed the port and ssl kwargs when I scanned over the repo, thanks!

**Comment by bachwehbi** [comment]
Cool!
Set top boxes can intercept clear-text connections and reply on behalf of the end system.
They can't with encrypted traffic.

I think it is time for me to address https://github.com/beebotte/bbt_python/issues/11 and add optional timeout arguments...
